# Generated by Django 5.0.4 on 2025-07-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.car'),
        ),
    ]
