# Generated by Django 5.0.4 on 2025-08-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_car_price'),
        ('policies', '0002_alter_insurancepolicy_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.offer'),
        ),
    ]
