# Generated by Django 5.0.4 on 2025-08-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_car_price'),
        ('policies', '0003_insurancepolicy_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.offer'),
        ),
    ]
