# Generated by Django 5.0.4 on 2025-08-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_insurancepolicy_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'permissions': [('view_policy', 'Can view policy details'), ('change_policy', 'Can modify policy details'), ('delete_policy', 'Can delete policy')]},
        ),
    ]
