# Generated by Django 5.0.4 on 2025-08-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_insurancepolicy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={},
        ),
    ]
