# Generated by Django 5.0.4 on 2025-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_offer_discounts'),
        ('policies', '0006_alter_insurancepolicy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applicable_to',
            field=models.ManyToManyField(blank=True, to='common.offer'),
        ),
    ]
