# Generated by Django 5.0.4 on 2025-08-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_offer_discounts'),
        ('policies', '0007_alter_discount_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.offer'),
        ),
    ]
