# Generated by Django 5.0.4 on 2025-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_alter_insurancepolicy_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('NEW_CLIENT', 'нов клиент'), ('CLIENT_AGE', 'възраст'), ('CAR_AGE', 'автомобил под 10г.')], max_length=12),
        ),
    ]
