# Generated by Django 5.0.4 on 2025-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_alter_discount_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
