# Generated by Django 5.0.4 on 2025-08-04 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_alter_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Размерът на отстъпката не може да бъде по-малък от 1%'), django.core.validators.MaxValueValidator(25, message='Размерът на отстъпката не може да бъде по-голям от 25%')]),
        ),
    ]
