# Generated by Django 5.0.4 on 2025-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_alter_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('NEW_CLIENT', 'нов клиент'), ('INSURANCE_AMOUNT', 'застрахователна сума над 10,000 лв.'), ('CAR_AGE', 'автомобил под 10г.')], unique=True),
        ),
    ]
