# Generated by Django 5.0.4 on 2025-08-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_alter_discount_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='applicable_to',
        ),
    ]
