# Generated by Django 5.0.4 on 2025-07-31 13:01

import InsuranceCompany.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', InsuranceCompany.accounts.managers.AppUserManager()),
            ],
        ),
    ]
