# Generated by Django 5.0.4 on 2025-07-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='no first name', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='no last name', max_length=100),
        ),
    ]
