# Generated by Django 5.0.4 on 2025-07-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_first_name_appuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
    ]
