# Generated by Django 5.0.4 on 2025-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_appuser_first_name_remove_appuser_last_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, default='Clients', help_text='Групите, към които принадлежи потребителят.', related_name='appuser_groups', related_query_name='appuser', to='auth.group', verbose_name='групи'),
        ),
    ]
