# Generated by Django 5.0.4 on 2025-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='testfield',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
