# Generated by Django 5.0.4 on 2025-07-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_car_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='testfield',
        ),
    ]
