# Generated by Django 5.0.4 on 2025-08-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
