# Generated by Django 5.0.4 on 2025-08-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_car_price'),
        ('policies', '0004_alter_insurancepolicy_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_policy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_to_policy', to='policies.insurancepolicy'),
        ),
    ]
