# Generated by Django 5.0.4 on 2025-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_offer_created_policy'),
        ('policies', '0006_alter_insurancepolicy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='policies.discount'),
        ),
    ]
