# Generated by Django 5.0.4 on 2025-08-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_offer_discounts'),
        ('policies', '0014_remove_discount_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='offers', to='policies.discount'),
        ),
    ]
