# Generated by Django 5.0.4 on 2025-08-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applied_discounts_text',
            field=models.TextField(blank=True, verbose_name='Приложени отстъпки'),
        ),
    ]
